//+mro-ignore
// DO NOT EDIT THIS FILE
// Generated by mro at 2021-07-21 09:56:44
package postgres

import (
	dbutil456 "github.com/seerx/gpa/rt/dbutil"
	models "github.com/seerx/gpa/examples/pratics/models"
	rt887 "github.com/seerx/gpa/rt"
	sql540 "database/sql"
)

type Delete struct {
	p *rt887.Provider
}

func (delete *Delete) DeleteByName(user *models.User, gender bool) (int64, error) {
	var err error
	var1 := "DELETE FROM user WHERE name=? "
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, user.Name)
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, err
	}
	return var3, nil
}

func (delete *Delete) DeleteByAgeAndCret(user *models.User) (int64, *models.User, error) {
	var err error
	
	var var4tp *dbutil456.TimeProp
	var4tp, err = dbutil456.NewTimeProp("DATETIME", true, "")
	if err != nil {
		return 0, nil, err
	}
	var4 := dbutil456.FormatColumnTime(delete.p.GetTimeStampzFormat(),
		delete.p.GetTimezone(),
		var4tp,
		user.Cret)
	var1 := "DELETE FROM user WHERE age=? And cret=? "
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, user.Age)
	var1Params = append(var1Params, var4)
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, nil, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, nil, err
	}
	return var3, nil, nil
}

func (delete *Delete) DeleteXByAge(age int, URL string) (int64, models.User, error) {
	var err error
	var1 := "DELETE FROM user WHERE age=? "
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, age)
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, models.User{}, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, models.User{}, err
	}
	return var3, models.User{}, nil
}

func (delete *Delete) DeleteName(user *models.User, name string, ages []int) (int64, error) {
	var err error
	var1 := "DELETE FROM \"user\" WHERE id=? and age in (@in-1626832605)"
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, user.ID)
	if len(ages) <= 0 {
		return 0, dbutil456.NewErrParamIsEmpty("ages")
	}
	var1 = dbutil456.TakePlaceHolder(var1, "@in-1626832605", len(ages))
	for _, varP := range ages {
		var1Params = append(var1Params, varP)
	}
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, err
	}
	return var3, nil
}

func (delete *Delete) DeleteXName(user *models.User, name string) (int64, error) {
	var err error
	var1 := "DELETE FROM user WHERE id = ? and age>?"
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, user.ID)
	var1Params = append(var1Params, user.Age)
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, err
	}
	return var3, nil
}

func (delete *Delete) DeleteAll() (int64, models.User, error) {
	var err error
	var1 := "DELETE FROM user"
	var var1Params []interface{}
	// where 参数
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, models.User{}, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, models.User{}, err
	}
	return var3, models.User{}, nil
}

func (delete *Delete) Delete1Name(id uint64) (int64, models.User, error) {
	var err error
	var1 := "DELETE FROM user WHERE id=?"
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, id)
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, models.User{}, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, models.User{}, err
	}
	return var3, models.User{}, nil
}

func (delete *Delete) Delete2Name(user models.User, id uint64) (int64, error) {
	var err error
	var1 := "DELETE FROM user WHERE id=?"
	var var1Params []interface{}
	// where 参数
	var1Params = append(var1Params, id)
	var var2 sql540.Result
	var2, err = delete.p.Executor().Exec(var1, var1Params...)
	if err != nil {
		return 0, err
	}
	var3, err := var2.RowsAffected()
	if err != nil {
		return var3, err
	}
	return var3, nil
}
