//+mro-ignore
// DO NOT EDIT THIS FILE
// Generated by mro at 2021-07-20 16:36:12
package postgres

import (
	context "context"
	dbutil694 "github.com/seerx/gpa/rt/dbutil"
	models "github.com/seerx/gpa/examples/pratics/models"
	rt847 "github.com/seerx/gpa/rt"
	sql300 "database/sql"
)

type Find struct {
	p *rt847.Provider
}

func (find *Find) FindA(ctx context.Context, id uint64) (*models.User, error){
    var err error
	sql := "SELECT id as id, name name, sum(age) as Age FROM user WHERE id=? group by name"
	var sqlParams []interface{}
	// where 参数
	sqlParams = append(sqlParams, id)
    
    var2 := find.p.Executor().QueryContextRow(ctx, sql, sqlParams...)
	
    var1 := &models.User{}
    if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age); err != nil {
        return nil, err
    }
    
	return var1, nil
}

func (find *Find) FindById(id uint64) (models.User, error){
    var err error
	sql := "SELECT id,name,age,gender,oka_us_url,cret,url FROM user WHERE id=? "
	var sqlParams []interface{}
	// where 参数
	sqlParams = append(sqlParams, id)
    
    var2 := find.p.Executor().QueryRow(sql, sqlParams...)
    var1 := models.User{}
    var var3 dbutil694.NullTime
    if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age, &var1.Gender, &var1.OkaUsURL, &var3, &var1.URL); err != nil {
        return models.User{}, err
    }
    
    var1.Cret = var3.Time()
	return var1, nil
}

func (find *Find) FindUsers(nm string) ([]*models.User, error){
    var err error
	sql := "SELECT id,name,age,gender,oka_us_url,cret,url FROM user WHERE name like ?"
	var sqlParams []interface{}
	// where 参数
	sqlParams = append(sqlParams, nm)
    
    var var2 *sql300.Rows
	var2, err = find.p.Executor().QueryRows(sql, sqlParams...)
	if err != nil {
		return nil,  err
	}
	
	var2Results := []*models.User{}
	for var2.Next() {
        var1 := &models.User{}
        var var3 dbutil694.NullTime
        if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age, &var1.Gender, &var1.OkaUsURL, &var3, &var1.URL); err != nil {
            return nil,  err
        }
        
        var1.Cret = var3.Time()
		var2Results = append(var2Results, var1)
	}
	return var2Results, nil
}

func (find *Find) FindUsers1(ids []uint64) ([]*models.User, error){
    var err error
	sql := "SELECT id,name,age,gender,oka_us_url,cret,url FROM user WHERE id in (@in-1626770172)"
	var sqlParams []interface{}
	// where 参数
	if len(ids) <= 0 {
		return nil, dbutil694.NewErrParamIsEmpty("ids")
	}
	sql = dbutil694.TakePlaceHolder(sql, "@in-1626770172", len(ids))
	for _, varP := range ids {
		sqlParams = append(sqlParams, varP)
	}
    
    var var2 *sql300.Rows
	var2, err = find.p.Executor().QueryRows(sql, sqlParams...)
	if err != nil {
		return nil,  err
	}
	
	var2Results := []*models.User{}
	for var2.Next() {
        var1 := &models.User{}
        var var3 dbutil694.NullTime
        if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age, &var1.Gender, &var1.OkaUsURL, &var3, &var1.URL); err != nil {
            return nil,  err
        }
        
        var1.Cret = var3.Time()
		var2Results = append(var2Results, var1)
	}
	return var2Results, nil
}

func (find *Find) FindMapByName(name string, kg func(*models.User) uint64) (map[uint64]*models.User, error){
    var err error
	sql := "SELECT id,name,age,gender,oka_us_url,cret,url FROM user WHERE name=? "
	var sqlParams []interface{}
	// where 参数
	sqlParams = append(sqlParams, name)
    
    var var2 *sql300.Rows
	var2, err = find.p.Executor().QueryRows(sql, sqlParams...)
	if err != nil {
		return nil,  err
	}
	
	var2Results := map[uint64]*models.User{}
	for var2.Next() {
        var1 := &models.User{}
        var var3 dbutil694.NullTime
        if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age, &var1.Gender, &var1.OkaUsURL, &var3, &var1.URL); err != nil {
            return nil,  err
        }
        
        var1.Cret = var3.Time()
		var2Results[kg(var1)] = var1
	}
	return var2Results, nil
}

func (find *Find) FindCbById(id uint64, fn func(*models.User) error) error{
    var err error
	sql := "SELECT id,name,age,gender,oka_us_url,cret,url FROM user WHERE id=? "
	var sqlParams []interface{}
	// where 参数
	sqlParams = append(sqlParams, id)
    
    var var2 *sql300.Rows
	var2, err = find.p.Executor().QueryRows(sql, sqlParams...)
	if err != nil {
		return  err
	}
	
	var1 := &models.User{}
	for var2.Next() {
        var var3 dbutil694.NullTime
        if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age, &var1.Gender, &var1.OkaUsURL, &var3, &var1.URL); err != nil {
            return  err
        }
        
        var1.Cret = var3.Time()
		if err = fn(var1); err != nil {
			return err
		}
	}
	return nil
}

func (find *Find) FindMapById(id uint64, fn func(*models.User) uint64) (map[uint64]*models.User, error){
    var err error
	sql := "SELECT id,name,age,gender,oka_us_url,cret,url FROM user WHERE id=? "
	var sqlParams []interface{}
	// where 参数
	sqlParams = append(sqlParams, id)
    
    var var2 *sql300.Rows
	var2, err = find.p.Executor().QueryRows(sql, sqlParams...)
	if err != nil {
		return nil,  err
	}
	
	var2Results := map[uint64]*models.User{}
	for var2.Next() {
        var1 := &models.User{}
        var var3 dbutil694.NullTime
        if err = var2.Scan(&var1.ID, &var1.Name, &var1.Age, &var1.Gender, &var1.OkaUsURL, &var3, &var1.URL); err != nil {
            return nil,  err
        }
        
        var1.Cret = var3.Time()
		var2Results[fn(var1)] = var1
	}
	return var2Results, nil
}
