//+gpa-ignore
// DO NOT EDIT THIS FILE
// Generated by gpa at 2021-07-16 11:16:10
package postgres

import (
	"github.com/seerx/gpa/rt"
	repos "github.com/seerx/gpa/examples/pratics/repos"
)

type repository struct {
	p *rt.Provider
	
	delete *Delete
	userRepo *UserRepo
	update *Update
}

func maker(p *rt.Provider) *repository {
	return &repository{p: p}
}

func init() {
	repos.Register("postgres", maker)
}


func (r *repository) Delete() *Delete {
	if r.delete == nil {
		r.delete = &Delete{p: r.p}
	}
	return r.delete
}

func (r *repository) UserRepo() *UserRepo {
	if r.userRepo == nil {
		r.userRepo = &UserRepo{p: r.p}
	}
	return r.userRepo
}

func (r *repository) Update() *Update {
	if r.update == nil {
		r.update = &Update{p: r.p}
	}
	return r.update
}
