//+mro-ignore
// DO NOT EDIT THIS FILE
// Generated by mro at 2021-07-15 17:15:23
package postgres

import (
	context "context"
	models "github.com/seerx/gpa/examples/pratics/models"
	rt81 "github.com/seerx/gpa/rt"
)

type UserRepo struct {
	p *