//+mro-ignore
// DO NOT EDIT THIS FILE
// Generated by mro at 2021-07-19 17:36:19
package postgres

import (
	models "github.com/seerx/gpa/examples/pratics/models"
	rt318 "github.com/seerx/gpa/rt"
	sql728 "database/sql"
)

type Teacher struct {
	p *rt318.Provider
}

func (teacher *Teacher) InsertTeacher(name string) (*models.Teacher, error) {
	var1 := &models.Teacher{}
	var1.Name = name
	var err error
	var var2 sql728.Result
	sql := "INSERT INTO teacher (name) VALUES (?) RETURNING id"
	var2, err = teacher.p.Executor().Exec(sql, name)
	if err != nil {
		return nil, err
	}
	
	var2InsertID, err := var2.LastInsertId()
	if err != nil {
		return nil, err
	}
	var1.ID = int(var2InsertID)
	
	return var1, err 
}
