//+gpa-ignore
// DO NOT EDIT THIS FILE
// Generated by gpa at {{.Time}}
package {{.packageName}}

import (
	"github.com/seerx/gpa/rt"
	{{.reposPackageName}} "{{.reposPackage}}"
)

type repository struct {
	p *rt.Provider
	{{ range $i, $v := .Repos }}
	{{$v.Instance}} *{{$v.Name -}}
	{{ end }}
}

func maker(p *rt.Provider) *repository {
	return &repository{p: p}
}

func init() {
	{{.reposPackageName}}.Register("{{.dialect}}", maker)
}

{{ range $i, $v := .Repos }}
func (r *repository) {{$v.Name}}() *{{$v.Name}} {
	if r.{{$v.Instance}} == nil {
		r.{{$v.Instance}} = &{{$v.Name}}{p: r.p}
	}
	return r.{{$v.Instance}}
}
{{ end }}